{
    "name": "JANAQ: Facturacion Electrónica Perú",
    "version": "18.0.1.0.1",
    "category": "Invoicing",
    "author": "JANAQ",
    "website": "http://www.janaq.com",
    "license": "OPL-1",
    "depends": [
        "base",
        "stock",
        "account",
        "purchase",
        "l10n_pe",
        "l10n_latam_base",
        "l10n_latam_invoice_document",
        "odoo_customize_partner_name",
        "product",
        "sale_stock"
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/res_groups.xml",
        "views/settings/res_config_settings.xml",
        "views/product/product_views.xml",
        "views/product/uom_views.xml",
        "views/stock/stock_warehouse_views.xml",
        "views/stock/stock_picking_views.xml",
        "views/sale/sale_order_views.xml",
        "views/account/account_journal_views.xml",
        "views/account/account_tax_views.xml",
        "views/account/view_acc_log_status.xml",
        "views/account/factura_views.xml",
        "views/account/boleta_views.xml",
        "views/account/nota_credito_views.xml",
        "views/account/menu.xml",
        "views/account/account_move_views.xml",
        "views/account/view_acc_com_baja.xml",
        "views/account/view_acc_parameters.xml",
        "views/account/account_detraction_view.xml",
        "views/catalogs/sunat_catalogs.xml",
        "views/company/company_views.xml",
        "views/partner/partner_views.xml",
        "views/partner/res_partner_bank.xml",
        "views/guia_remision/guia_remision_electronica.xml",
        "views/guia_remision/vehicle_views.xml",
        "report/ir_actions_report.xml",
        "report/validate_cpe_template.xml",
        "cron/validez_comprobante_cron.xml",
        "data/l10n.xml",
        "data/catalogs.xml",
        "data/catalog_03.xml",
        "data/detraction.xml",
        "data/transfer_reason.xml",
        "data/transport_type.xml",
        "data/related_document.xml",
        "data/account_parameters.xml",
    ],
}